name: climber_eye
description: "Simple application to compare two videos simultaneously."
publish_to: 'none'
version: 1.0.0+1
homepage: https://github.com/adrianlzt/climber_eye
repository: https://github.com/adrianlzt/climber_eye

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  video_player: ^2.8.1
  file_picker: ^9.1.0
  another_xlider: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
